# This add-on's default property values are declared in `charts/add-ons/prometheus/values.yaml`.
# If installing/upgrading with Helm, you can override them through the usual `--set` or `-f` flags
# when installing with the parent linkerd2 chart
# Do not override them in this file!
# If installing/upgrading with linkerd's CLI, use the `--addon-config` flag.
image: prom/prometheus:v2.19.3
args:
  storage.tsdb.path: /data
  storage.tsdb.retention.time: 6h
  config.file: /etc/prometheus/prometheus.yml
  log.level: info
globalConfig:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
#
## For Private docker registries, authentication is needed.
# If the control plane service images are pulled from a
# protected docker registry, define pull secrets as follows:
#
#imagePullSecrets:
#    - name: my-private-docker-registry-login-secret
#
# The pull secrets are applied to the respective service accounts
# which will further orchestrate the deployments.
imagePullSecrets: []
